version: '3.8'
services:
  node:
    image: 'node:16-alpine'
    user: 'node'
    working_dir: '/home/node/app'
    environment:
     - "NODE_ENV=development"
    ports:
     - "3700:3700"
    volumes:
     - ./:/home/node/app
    command: 'npm start'
