version: '3.8'
services:
  node:
    image: 'node:16-alpine'
    user: 'node'
    working_dir: '/home/node/app'
    environment:
      - "NODE_ENV=development"
    expose:
      - '3700'
    ports:
      - "3700:3700"
    volumes:
      - ./:/home/node/app
    command: 'npm start'

#version: '2.4'  //this is how the file should be. version doesn't really matter
#services:
#  snake:
#    image: 'eapen303/nodejsapp:latest'
#    environment:
#     - "PORT:3700"
#    ports:
#     - "80:3700"
#    volumes:
#     - ./:/index.js
